<?php

$this->extend('layouts.app');
?>

<?php if (isset($collection) && count($collection)):?>

  <div id="carousel-maxmilhas" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <?php $activeClass = 'class="active"';?>
      <?php foreach ($collection as  $i => $model):?>
        <li data-target="#carousel-maxmilhas" data-slide-to="<?php echo  $i;?>" <?php echo $activeClass; ?>></li>
        <?php $activeClass = '';?>
      <?php endforeach;?>
    </ol>
    <div class="carousel-inner" role="listbox">
        <?php $activeClass = 'active';?>
        <?php foreach ($collection as  $i => $model):?>
      <div class="item <?php echo $activeClass;?>">
        <img src='<?php echo $this->htmlEscape($model->getImageUrl());?>' alt="<?php echo $this->htmlEscape($model->label);?>">
      </div>
        <?php $activeClass = '';?>
      <?php endforeach;?>
    </div>
    <a class="left carousel-control" href="#carousel-maxmilhas" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#carousel-maxmilhas" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
<?php endif;?>
