<section class="form col-md-6 col-md-offset-3">


  <form action="<?php echo $this->htmlEscape($url);?>" method="POST" enctype="multipart/form-data">
    <?php echo csrf_field();?>
    <?php echo method_field($method);?>
  <div class="form-group">
        <label for="label">
          Rótulo da Imagem
        </label>
          <input id="label" type="text" name="label" class="form-control" value='<?php echo $this->htmlEscape($model->label);?>' >

  </div>

  <div class="form-group">
        <label for="file">
          Arquivo
          <?php if ($model->getImageUrl()):?>
            <img class="thumb img-thumbnail"
              src="<?php echo $this->htmlEscape($model->getImageUrl());?>"
              alt="<?php echo $this->htmlEscape($model->label);?>"       >
          <?php endif;?>
        </label>
        <input id="file" type="file" name="file" class="form-control" >




  </div>

  <button type="submit" class="btn btn-primary">
      <i class='fa <?php echo $this->htmlEscape($submit['icon']);?>'></i>
      <?php echo $this->htmlEscape($submit['label']);?>
  </button>

  </form>

</section>
