<?php $this->extend('layouts.app', ['title' => 'Gerenciar Images']);?>

<?php
$params = [
  'collection' => $collection,
  'attributes'  => [
    'label' => 'Label',
    'path' => [
        'label' => 'Imagem',
        'format' => function ($v, $model) {
            $v = $model->getImageUrl();

           return "<img class='thumb img-thumbnail' src='{$v}' alt='{$model->label}' >";
        },
      ],
  ],
  'actions' => [
    'edit'   => ['url' => '/images/:id/edit'],
    'destroy' => ['url' => '/images/:id'],

  ],
];?>



  <div class="pull-right ">
    <a href="/images/create" class="btn btn-success">
      <i class="fa fa-add" aria-hidden="true"></i>
      Cadastrar nova Imagem
     </a>
  </div>





<?php echo $this->partial('utils.grid.grid', $params);?>
