<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="<?php echo csrf_token() ?>">
    <title>
      <?php  echo $title;?> Title
    </title>

    <link rel="stylesheet" type="text/css" href="<?php echo assets_url('libs/bootstrap/dist/css/bootstrap.css') ?>">
    <link rel="stylesheet" type="text/css" href="<?php  echo assets_url('libs/bootstrap/dist/css/bootstrap-theme.css') ?>" >
    <link rel="stylesheet" type="text/css" href="<?php  echo assets_url('css/app.css') ?>" >

  <!-- Fonts -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css" integrity="sha384-XdYbMnZ/QjLh6iI4ogqCTaIjrFk87ip+ekIjefZch0Y+PvJ8CDYtEs1ipDmPorQ+" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700">

  </head>
<body>

    <?php echo $this->partial('layouts.navigation.top');?>
    <div class="clearfix">
      &nbsp;
    </div>
    <div class="main-container">
      <div class="container">
        <div class="row">

            <section class="content col-md-12">
                <?php echo $content;?>
            </section>
          </div>
       </div>
   </div>


       <script type="text/javascript"  src="<?php echo assets_url('libs/jquery/dist/jquery.js');?>" ></script>
       <script type="text/javascript"  src="<?php echo assets_url('libs/bootstrap/dist/js/bootstrap.js');?>" ></script>
       <script type="text/javascript"  src="<?php echo assets_url('js/app.js');?>" ></script>
</body>
</html>
